= {Chapter} 7 | {chapterTitle}
:showtitle:
:table-caption!:

== 7.1 {7-1-title}

{7-1-p1}

{7-1-p2}

=== 7.1.1 {7-1-1-title}

{7-1-1-p}

[list-[lower-alpha]]
a. {7-1-1-a-text}
+
[.samplebox]
[cols="1,1"]
|===
| {7-1-1-a-sample1_ga} | {7-1-1-a-sample1} 
| {7-1-1-a-sample2_ga} | {7-1-1-a-sample2} 
| {7-1-1-a-sample3_ga} | {7-1-1-a-sample3} 
| {7-1-1-a-sample4_ga} | {7-1-1-a-sample4} 
|===

b. {7-1-1-b-text}
+
[.samplebox]
[cols="1,1"]
|===
| {7-1-1-b-sample1_ga} | {7-1-1-b-sample1}
| {7-1-1-b-sample2_ga} | {7-1-1-b-sample2}
|===

c. {7-1-1-c-text}
+
[.samplebox]
[cols="1,1"]
|===
| {7-1-1-c-sample1_ga} | {7-1-1-c-sample1}
| {7-1-1-c-sample2_ga} | {7-1-1-c-sample2}
| {7-1-1-c-sample3_ga} | {7-1-1-c-sample3}
| {7-1-1-c-sample4_ga} | {7-1-1-c-sample4}
|===

d. {7-1-1-d-text}
+
[.samplebox]
[cols="1,1"]
|===
| {7-1-1-d-sample1_ga} | {7-1-1-d-sample1}
| {7-1-1-d-sample2_ga} | {7-1-1-d-sample2}
| {7-1-1-d-sample3_ga} | {7-1-1-d-sample3}
| {7-1-1-d-sample4_ga} | {7-1-1-d-sample4}
| {7-1-1-d-sample5_ga} | {7-1-1-d-sample5}
| {7-1-1-d-sample6_ga} | {7-1-1-d-sample6}
|===

e. {7-1-1-e-text}
+
[.samplebox]
[cols="1,1"]
|===
| {7-1-1-e-sample1_ga} | {7-1-1-e-sample1}
| {7-1-1-e-sample2_ga} | {7-1-1-e-sample2}
|===

f. {7-1-1-f-text}
+
[.samplebox]
[cols="1,1"]
|===
| {7-1-1-f-sample1_ga} | {7-1-1-f-sample1}
| {7-1-1-f-sample2_ga} | {7-1-1-f-sample2}
| {7-1-1-f-sample3_ga} | {7-1-1-f-sample3}
| {7-1-1-f-sample4_ga} | {7-1-1-f-sample4}
| {7-1-1-f-sample5_ga} | {7-1-1-f-sample5}
|===

g. {7-1-1-g-text}
+
[.samplebox]
[cols="1,1"]
|===
| {7-1-1-g-sample1_ga} | {7-1-1-g-sample1}
| {7-1-1-g-sample2_ga} | {7-1-1-g-sample2}
| {7-1-1-g-sample3_ga} | {7-1-1-g-sample3}
| {7-1-1-g-sample4_ga} | {7-1-1-g-sample4}
| {7-1-1-g-sample5_ga} | {7-1-1-g-sample5}
|===

h. {7-1-1-h-text}
+
[.samplebox]
[cols="1,1"]
|===
| {7-1-1-h-sample1_ga} | {7-1-1-h-sample1}
| {7-1-1-h-sample2_ga} | {7-1-1-h-sample2}
| {7-1-1-h-sample3_ga} | {7-1-1-h-sample3}
| {7-1-1-h-sample4_ga} | {7-1-1-h-sample4}
| {7-1-1-h-sample5_ga} | {7-1-1-h-sample5}
| {7-1-1-h-sample6_ga} | {7-1-1-h-sample6}
| {7-1-1-h-sample7_ga} | {7-1-1-h-sample7}
| {7-1-1-h-sample8_ga} | {7-1-1-h-sample8}
| {7-1-1-h-sample9_ga} | {7-1-1-h-sample9}
|===
i. {7-1-1-i-text}
+
[.samplebox]
[cols="1,1"]
|===
| {7-1-1-i-sample1_ga} | {7-1-1-i-sample1}
| {7-1-1-i-sample2_ga} | {7-1-1-i-sample2}
| {7-1-1-i-sample3_ga} | {7-1-1-i-sample3}
| {7-1-1-i-sample4_ga} | {7-1-1-i-sample4}
| {7-1-1-i-sample5_ga} | {7-1-1-i-sample5}
|===

'''

== 7.2 {7-2-title}

[list-[lower-alpha]]
. {7-2-a-p}
. {7-2-b-p1}
[list-[lower-roman]]
.. {7-2-b-i-p}
.. {7-2-b-ii-p}
.. {7-2-b-iii-p}
.. {7-2-b-iv-p}

+
{7-2-b-p2}

=== 7.2.1 {7-2-1-title}

==== A {7-2-1-A-title}

{7-2-1-A-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7A</strong> {Table7A-caption}
  </caption>
  <colgroup>
    <col class="w-3/16">
    <col class="w-3/16">
    <col class="w-10/16">
  </colgroup>
  <thead>
  <tr>
    <th colspan="3" class="text-xl py-2">{Table7A-header}</th>
  </tr>
  <tr>
    <th colspan="3">{Table7A-subheader}</th>
  </tr></thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <th>is</th>
    <td>
        <ul>
            <li><strong>Is</strong> talamh maith anois é.</li>
            <li>Ealaíontóir maith <strong>is</strong> ea ise.</li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <th>ní</th>
    <td>
        <ul>
            <li><strong>Ní</strong> bia bainne is <strong>ní</strong> bainne bláthach.</li>
            <li><strong>Ní</strong> hé a d'inis an bhréag sin.</li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Interrogative} {Positive}</td>
    <th>an</th>
    <td>
        <ul>
            <li><strong>An</strong> í Bríd an múinteoir?</li>
            <li><strong>An</strong> fada go dtiocfaidh sé?</li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Interrogative} {Negative}</td>
    <th>nach</th>
    <td>
        <ul>
            <li><strong>Nach</strong> (é) Seán atá ina mhúinteoir?</li>
            <li><strong>Nach</strong> (í) Siobhán a bheidh ann amárach?</li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

==== B {7-2-1-B-title}

{7-2-1-B-p1}

[list-[lower-alpha]]
. {7-2-1-B-a-p}
. {7-2-1-B-b-p}
+
[list-[lower-roman]]
.. {7-2-1-B-b-i-p}
.. {7-2-1-B-b-ii-p}
.. {7-2-1-B-b-iii-p}
.. {7-2-1-B-b-iv-p}
. {7-2-1-B-c-p}
[list-[lower-roman]]
.. {7-2-1-B-c-i-p}
.. {7-2-1-B-c-ii-p}
.. {7-2-1-B-c-iii-p}
.. {7-2-1-B-c-iv-p}
. {7-2-1-B-d-p}

{7-2-1-B-p2}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7B</strong> {Table7B-caption}
  </caption>
  <thead>
  <tr>
    <th colspan="3" class="text-xl py-2">{Table7B-header}</th>
  </tr>
  <tr>
    <th>{BeforeConsonantQualified}</th>
    <th colspan="2">{BeforeVowelQualified}</th>
  </tr>
  <tr>
    <th class="bg-stone-300 text-black">ba</th>
    <th class="bg-stone-300 text-black">b'</th>
    <th class="bg-stone-300 text-black">ba (ab)</th>
  </tr></thead>
<tbody>
  <tr>
    <td>
        <ul>
            <li><strong>Ba</strong> mhian liomsa labhairt.</li>
            <li><strong>Ba</strong> fhlaithiúil go deo a chaith siad liom.</li>
            <li><strong>Ba</strong> bheag an chabhair dom é dá bhfaighinn in am é fiú.</li>
        </ul>
    </td>
    <td>
        <ul>
            <li><strong>B'</strong>álainn an pictiúr é mura mbeadh an polla sin sa chúlra.</li>
            <li><strong>B'</strong>aoibhinn linn a bheith ag éisteacht leis gach oíche.</li>
            <li><strong>B'</strong>eol dúinn go dtéadh sí an cóngar nuair a bhíodh sé tirim.</li>
        </ul>
    </td>
    <td>
        <ul>
            <li><strong>Ba</strong> é an Rúnaí a cheartódh é sa chás sin.</li>
            <li>Ceannaire maith <strong>ba/ab</strong> ea í siúd.</li>
            <li><strong>Ba</strong> aici a bhí an ceart.</li>
            <li><strong>Ba</strong> as Gaillimh é.</li>
            <li><strong>Ba</strong> ó Bhaile Átha Cliath í.</li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

{7-2-1-B-p2}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7C</strong> {Table7C-caption}
  </caption>
  <thead>
  <tr>
    <th colspan="5" class="text-xl py-2">{Table7C-header}</th>
  </tr>
  <tr>
    <th></th>
    <th colspan="2">{BeforeConsonantQualified}</th>
    <th colspan="2">{BeforeVowelQualified}</th>
  </tr></thead>
<tbody>
  <tr>
    <td>{Negative}</td>
    <td class="font-bold bg-stone-300">níor</td>
    <td><strong>Níor</strong> mhaith léi go dtarlódh sé sin.</td>
    <td class="font-bold bg-stone-300">níorbh</td>
    <td><strong>Níorbh</strong> aon dóithín é.</td>
  </tr>
  <tr>
    <td>{Interrogative} {Positive}</td>
    <td class="font-bold bg-stone-300">ar</td>
    <td><strong>Ar</strong> dheacair leat é?</td>
    <td class="font-bold bg-stone-300">arbh</td>
    <td><strong>Arbh</strong> fhearr é mar atá sé?</td>
  </tr>
  <tr>
    <td>{Interrogative} {Negative}</td>
    <td class="font-bold bg-stone-300">nár</td>
    <td><strong>Nár</strong> dhána an mhaise dó é!</td>
    <td class="font-bold bg-stone-300">nárbh</td>
    <td><strong>Nárbh</strong> é an diabhal é?</td>
  </tr>
</tbody>
</table>
++++

=== 7.2.2 {7-2-2-title}

==== A {7-2-2-A-title}

{7-2-2-A-p1}

[list-[lower-alpha]]
. {7-2-2-A-a-p}
. {7-2-2-A-b-p}
[list-[lower-roman]]
.. {7-2-2-A-b-i-p}
.. {7-2-2-A-b-ii-p}
.. {7-2-2-A-b-iii-p}
.. {7-2-2-A-b-iv-p}
.. {7-2-2-A-b-v-p}
. {7-2-2-A-c-p}
[list-[lower-roman]]
.. {7-2-2-A-c-i-p}
.. {7-2-2-A-c-ii-p}
.. {7-2-2-A-c-iii-p}
.. {7-2-2-A-c-iv-p}
.. {7-2-2-A-c-v-p}
.. {7-2-2-A-c-vi-p}

{7-2-2-A-p2}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7D</strong> {Table7D-caption}
  </caption>
  <colgroup>
    <col class="w-1/7">
    <col class="w-2/7">
    <col class="w-2/7">
    <col class="w-2/7">
  </colgroup>
  <thead>
    <tr>
        <th colspan="4" class="text-xl py-2">{Table7D-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonant}</th>
        <th colspan="2">{BeforeVowel}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <th class="bg-stone-300"></th>
    <th class="bg-stone-300">gur</th>
    <th class="bg-stone-300">gur</th>
    <th class="bg-stone-300">gurb</th>
  </tr>
  <tr>
    <td>{Positive}</td>
    <td>
        <ul>
            <li>Ceapann siad <strong>gur</strong> múinteoir maith é Seán.</li>
            <li>Is dóigh liom <strong>gur</strong> tráthnóna amárach a bheidh an cruinniú ann.</li>
        </ul>
    </td>
    <td>
        <ul>
            <li>Ceapann siad <strong>gur</strong> altra é.</li>
            <li>Sílim <strong>gur</strong> acu a bheidh an bua.</li>
        </ul>
    </td>
    <td>
        <ul>
            <li>Is dóigh leis <strong>gurb</strong> álainn an lá é.</li>
            <li>Ní dóigh liom <strong>gurb</strong> ionann iad.</li>
            <li>Ní foláir <strong>gurb</strong> acmhainn dóibh.</li>
            <li>Más rud é <strong>gurb</strong> éigean dóibh.</li>
        </ul>
    </td>
  </tr>
  <tr>
    <th class="bg-stone-300"></th>
    <th class="bg-stone-300" colspan=3>nach</th>
  </tr>
  <tr>
    <td>{Negative}</td>
    <td colspan=3>
        <ul>
            <li>Deir sé <strong>nach</strong> amárach a bheidh an cluiche ar siúl.</li>
            <li>Tuigimid <strong>nach</strong> é deireadh an domhain é má chaillimid.</li>
            <li>Síleann siad <strong>nach</strong> taighdeoir maith é.</li>
            <li>Dar liom <strong>nach</strong> cuan sábháilte é.</li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

==== B {7-2-2-B-title}

{7-2-2-B-p}

[list-[lower-alpha]]
. {7-2-2-B-a-title}
+
{7-2-2-B-a-p1}
[list-[lower-roman]]
.. {7-2-2-B-a-i}
.. {7-2-2-B-a-ii}

+
{7-2-2-B-a-p2}

+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7E</strong> {Table7E-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="3" class="text-xl py-2">{Table7E-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th class="bg-stone-300"></th>
      <th class="bg-stone-300">gur</th>
      <th class="bg-stone-300">gurbh</th>
    </tr>
    <tr>
      <td>{Positive}</td>
      <td>
          <ul>
              <li>Dúirt Eoin <strong>gur</strong> cheart é a dhíol.</li>
              <li>Cheapamar <strong>gur</strong> fhlaithiúil an duine ab ea é.</li>
          </ul>
      </td>
      <td>
          <ul>
              <li>Dhearbhaigh sé <strong>gurbh</strong> fhéimheach é.</li>
              <li>Dúirt sí <strong>gurbh</strong> é leas an phobail é.</li>
          </ul>
      </td>
    </tr>
  </tbody>
</table>
++++

. {7-2-2-B-b-title}
+
{7-2-2-B-b-p1}
[list-[lower-roman]]
.. {7-2-2-B-b-i}
.. {7-2-2-B-b-ii}
[.list-dots]
*** {7-2-2-B-b-ii-1}
*** {7-2-2-B-b-ii-2}
*** {7-2-2-B-b-ii-3}
*** {7-2-2-B-b-ii-4}
.. {7-2-2-B-b-iii}
[.list-dots]
*** {7-2-2-B-b-iii-1}
*** {7-2-2-B-b-iii-2}
*** {7-2-2-B-b-iii-3}
*** {7-2-2-B-b-iii-4}

+
{7-2-2-B-b-p2}

+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7F</strong> {Table7F-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="3" class="text-xl py-2">{Table7F-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <th class="bg-stone-300"></th>
    <th class="bg-stone-300">go mba</th>
    <th class="bg-stone-300">go mba <span class="font-normal">nó</span> go mb'</th>
  </tr>
  <tr>
    <td>{Positive}</td>
    <td>
        <ul>
            <li>Dúirt Eoin <strong>go mba</strong> cheart é a dhíol.</li>
            <li>Sílim <strong>go mba</strong> fhliúit dhaor a cheannaigh sé.</li>
        </ul>
    </td>
    <td>
        <ul>
            <li>Dhearbhaigh sé <strong>go mb'</strong>fhéimheach é.</li>
            <li>Dúirt sí <strong>go mba</strong> é leas an phobail é.</li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

. {7-2-2-B-c-title}
+
{7-2-2-B-c-p1}
+
--
[list-[lower-roman]]
.. {7-2-2-B-c-i}
.. {7-2-2-B-c-ii}
--
+
{7-2-2-B-c-p2}

+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7G</strong> {Table7G-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="3" class="text-xl py-2">{Table7G-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <th class="bg-stone-300"></th>
    <th class="bg-stone-300">nár</th>
    <th class="bg-stone-300">nárbh</th>
  </tr>
  <tr>
    <td>{Positive}</td>
    <td>
        <ul>
            <li>Ba léir <strong>nár</strong> dhochtúir cáilithe é.</li>
            <li>Dúirt sí <strong>nár</strong> fhlichshneachta ceart é.</li>
        </ul>
    </td>
    <td>
        <ul>
            <li>Dúirt sé <strong>nárbh</strong> fhéidir é a dhéanamh.</li>
            <li><strong>Nárbh</strong> iontach an clár faisnéise é sin?</li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

=== 7.2.3 {7-2-3-title}

==== A {7-2-3-A-title}

{7-2-3-A-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7H</strong> {Table7H-caption}
  </caption>
  <colgroup>
    <col>
    <col>
    <col class="w-4/6">
  </colgroup>
  <thead>
    <tr>
        <th colspan="3" class="text-xl py-2">{Table7H-header}</th>
    </tr>
    <tr>
        <th colspan="3">{Table7H-subheader}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <th>is</th>
    <td>
        <ul>
            <li>Labhair leis an bhfear sin <strong>is</strong> uncail leat.</li>
            <li>An bhean <strong>is</strong> cara leat a d'eagraigh é.</li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <th>nach</th>
    <td>
        <ul>
            <li>Ní cheadófar d'aon duine <strong>nach</strong> ball é nó í fanacht sa seomra.</li>
            <li>Céard faoi na daoine <strong>nach</strong> comhaltaí iad?</li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

==== B {7-2-3-B-title}

{7-2-3-B-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7I</strong> {Table7I-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="5" class="text-xl py-2">{Table7I-header}</th>
    </tr>
    <tr>
        <th></th>
        <th colspan=2>{BeforeConsonantQualified}</th>
        <th colspan=2>{BeforeVowelQualified}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <td class="bg-stone-300 font-bold">ba</td>
    <td>
        <ul>
            <li>Cad é <strong>ba</strong> mhaith leat?</li>
            <li>Sin an carr <strong>ba</strong> cheart duit a cheannach.</li>
        </ul>
    </td>
    <td class="bg-stone-300 font-bold">ab</td>
    <td>
        <ul>
            <li>Sin rud <strong>ab</strong> éasca a rá.</li>
            <li>Má bhí leabhar ann riamh <strong>ab</strong> fhiú a léamh, seo é.</li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <td class="bg-stone-300 font-bold">nár</td>
    <td>
        <ul>
            <li>Níor dhóigh siad aon bhreosla <strong>nár</strong> ghual (é).</li>
            <li>Níor ceannaíodh bó <strong>nár</strong> bhó mhaith (í).</li>
        </ul>
    </td>
    <td class="bg-stone-300 font-bold">nárbh</td>
    <td>
        <ul>
            <li>Is é sin an Teachta <strong>nárbh</strong> Aire riamh (é).</li>
            <li>Níor cheannaigh siad úlla <strong>nárbh</strong> úlla dearga (iad).</li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

=== 7.2.4 {7-2-4-title}

==== A {7-2-4-A-title}

{7-2-4-A-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7J</strong> {Table7J-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="5" class="text-xl py-2">{Table7J-header}</th>
    </tr>
    <tr>
        <th></th>
        <th colspan=2>{BeforeConsonant}</th>
        <th colspan=2>{BeforeVowel}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <td class="bg-stone-300 font-bold">ar</td>
    <td>
        <ul>
            <li>Ná bac leis sin; sin eolas <strong>ar</strong> cuma faoi.</li>
            <li>Is é sin an té <strong>ar</strong> dó an leabhar.</li>
        </ul>
    </td>
    <td class="bg-stone-300 font-bold">arb</td>
    <td>
        <ul>
            <li>Is í sin an bhean <strong>arb</strong> iriseoir a deartháir.</li>
            <li>An bhfuil an té <strong>arb</strong> eol dó an freagra sa seomra?</li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <td class="bg-stone-300 font-bold">nach</td>
    <td>
        <ul>
            <li>Cár imigh an duine <strong>nach</strong> féidir labhairt leis?</li>
            <li>Is iad sin na daoine <strong>nach</strong> mian leo leanúint ar aghaidh.</li>
        </ul>
    </td>
    <td class="bg-stone-300 font-bold">nach</td>
    <td>
        <ul>
            <li>Is í sin an bhean <strong>nach</strong> iriseoir a deartháir.</li>
            <li>Sin é an t-aisteoir <strong>nach</strong> eol dó a chuid línte.</li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

==== B {7-2-4-B-title}

{7-2-4-B-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7K</strong> {Table7K-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="5" class="text-xl py-2">{Table7K-header}</th>
    </tr>
    <tr>
        <th></th>
        <th colspan="2">{BeforeConsonantQualified}</th>
        <th colspan="2">{BeforeVowelQualified}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <td class="bg-stone-300 font-bold">ar</td>
    <td>
        Sin í an bhean <strong>ar</strong> mhór aici do chabhair. 
    </td>
    <td class="bg-stone-300 font-bold">arb</td>
    <td>
        Léigh sí gach leabhar <strong>arbh</strong> fhiú trácht air.
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <td class="bg-stone-300 font-bold">nach</td>
    <td>
        Cá bhfuil na daoine <strong>nár</strong> mhaith leo labhairt? 
    </td>
    <td class="bg-stone-300 font-bold">nach</td>
    <td>
        Ba dhána iad na páistí <strong>nárbh</strong> áil leo dul ar scoil.
    </td>
  </tr>
</tbody>
</table>
++++

=== 7.2.5 {7-2-5-title}

==== A {7-2-5-A-title}

[list-[lower-alpha]]
. {7-2-5-A-a-p}
[list-[lower-roman]]
.. {7-2-5-A-a-i-p}
.. {7-2-5-A-a-ii-p}
.. {7-2-5-A-a-iii-p}
. {7-2-5-A-b-p}
[list-[lower-roman]]
.. {7-2-5-A-b-i-p}
.. {7-2-5-A-b-ii-p}
.. {7-2-5-A-b-iii-p}
.. {7-2-5-A-b-iv-p}
.. {7-2-5-A-b-v-p}
.. {7-2-5-A-b-vi-p}
. {7-2-5-A-c-p}
[list-[lower-roman]]
.. {7-2-5-A-c-i-p}
.. {7-2-5-A-c-ii-p}
.. {7-2-5-A-c-iii-p}

{7-2-5-A-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7L</strong> {Table7L-caption}
  </caption>
  <colgroup>
    <col style="width: 50%"/>
    <col style="width: 50%"/>
  </colgroup>
  <thead>
    <tr>
        <th colspan="2" class="text-xl font-bold">{Table7L-header}</th>
    </tr>
    <tr>
        <th>{Table7L-subheader-col1}</th>
        <th>{Table7L-subheader-col2}</th>
    </tr></thead>
<tbody>
  <tr>
    <td>{Table7L-row1-col1}</td>
    <td>{Table7L-row1-col2}</td>
  </tr>
  <tr>
    <td>{Table7L-row2-col1}</td>
    <td>{Table7L-row2-col2}</td>
  </tr>
  <tr>
    <td>{Table7L-row3-col1}</td>
    <td>{Table7L-row3-col2}</td>
  </tr>
  <tr>
    <td>{Table7L-row4-col1}</td>
    <td></td>
  </tr>
  <tr>
    <td>{Table7L-row5-col1}</td>
    <td></td>
  </tr>
  <tr>
    <td>{Table7L-row6-col1}</td>
    <td></td>
  </tr>
</tbody>
</table>
++++

==== B {7-2-5-B-title}

{7-2-5-B-p}

'''

== 7.3 {7-3-title}

=== 7.3.1 {7-3-1-title}

==== A {7-3-1-A-title}

{7-3-1-A-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7M</strong> {Table7M-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=3 class="text-xl font-bold">{Table7M-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonant}</th>
        <th>{BeforeVowel}</th>
    </tr></thead>
<tbody>
  <tr>
    <th>cá</th>
    <td><strong>Cá</strong> miste duit?</td>
    <td><strong>Cárb</strong> as é?/<strong>Cárb</strong> as duit?</td>
  </tr>
  <tr>
    <th>cé</th>
    <td><strong>Cé</strong> dó a dtabharfaidh sé é?</td>
    <td><strong>Cérb</strong> iad?</td>
  </tr>
</tbody>
</table>
++++

==== B {7-3-1-B-title}

{7-3-1-B-p1}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7N</strong> {Table7N-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=3 class="text-xl font-bold">{Table7N-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr></thead>
<tbody>
  <tr>
    <th>cá</th>
    <td><strong>Cár</strong> thairbhe duit é?</td>
    <td><strong>Cárbh</strong> aois é?</td>
  </tr>
  <tr>
    <th>cé</th>
    <td><strong>Cér</strong> díobh í?</td>
    <td><strong>Cérbh</strong> é an fear sin?</td>
  </tr>
</tbody>
</table>
++++

{7-3-1-p}

=== 7.3.2 {7-3-2-title}

==== A {7-3-2-A-title}

{7-3-2-A-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7O</strong> {Table7O-caption}
  </caption>
  <colgroup>
    <col class="w-20">
  </colgroup>
  <thead>
    <tr>
        <th colspan=3 class="text-xl font-bold">{Table7O-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonant}</th>
        <th>{BeforeVowel}</th>
    </tr></thead>
<tbody>
    <tr>
        <th>de/do</th>
        <td>Cuirfear deireadh leis an imscrúdú an tréimhse <strong>dar</strong> críoch an 1ú lá de mhí Iúil.</td>
        <td>Tá aithne agam ar bhean <strong>darb</strong> ainm Máire Ní Chiarragáin.</td>
    </tr>
    <tr>
        <th>faoi</th>
        <td>Cé acu dlí an dlí <strong>faoinar</strong> féidir í a chúiseamh?</td>
        <td>Is ábhar é sin <strong>faoinarb</strong> éasca labhairt.</td>
    </tr>
    <tr>
        <th>i</th>
        <td>Is í sin an oifig <strong>inar</strong> mian léi a bheith ag obair.</td>
        <td>Is foirgneamh é sin <strong>inarb</strong> annamh ar cuairt é.</td>
    </tr>
    <tr>
        <th>le</th>
        <td>Is iomaí córas atá ar fáil <strong>lenar</strong> féidir rialú a dhéanamh.</td>
        <td>Dúirt sí a rogha rud, ar neamhchead don té <strong>lenarb</strong> olc.</td>
    </tr>
    <tr>
        <th>ó</th>
        <td>Beidh siad i scríbhinn nó i bhfoirm <strong>ónar</strong> féidir taifead scríofa a tháirgeadh.</td>
        <td>Bhí sé i dteannta an dreama <strong>ónarb</strong> áil leis teitheadh.</td>
    </tr>
    <tr>
        <th>trí</th>
        <td>Faightear réidh le gach meán eile <strong>trínar</strong> féidir aon ní den sórt sin a scriosadh.</td>
        <td>Cén fhoirmle atá agat <strong>trínarb</strong> éasca an cheist a fhreagairt?</td>
    </tr>
</tbody>
</table>
++++

==== B {7-3-2-B-title}

{7-3-2-B-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7P</strong> {Table7P-caption}
  </caption>
  <colgroup>
    <col class="w-20">
  </colgroup>
  <thead>
    <tr>
        <th colspan=3 class="text-xl font-bold">{Table7P-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr></thead>
<tbody>
    <tr>
        <th>de/do</th>
        <td>Cuireadh iniúchadh i gcrích don bhliain <strong>dar</strong> chríoch an 8 Márta 1998.</td>
        <td>Is buachaill <strong>darbh</strong> ainm Gearóid a bhí i láthair.</td>
    </tr>
    <tr>
        <th>faoi</th>
        <td>Liostaíodh na coinníollacha <strong>faoinar</strong> chomhaltaí iad na daoine sin.</td>
        <td>Luadh an dáta <strong>faoinarbh</strong> fhéidir litir a chur faoi bhráid an Aire.</td>
    </tr>
    <tr>
        <th>i</th>
        <td>D'fhéadfaí an cás a éisteacht i gcás <strong>inar</strong> fhreagróir an duine sin.</td>
        <td>Is cás é sin <strong>inarbh</strong> fhostaí d'úinéir na feithicle a cúisíodh.</td>
    </tr>
    <tr>
        <th>le</th>
        <td>Is í sin an eagraíocht <strong>lenar</strong> ghníomhaire é.</td>
        <td>Sin í an fhoireann <strong>lenarbh</strong> áil liom imirt.</td>
    </tr>
    <tr>
        <th>ó</th>
        <td>Chuaigh sé ar ais go dtí an tír <strong>ónar</strong> dhíbeartach é.</td>
        <td>Tabhair faisnéis dom faoin iasacht agus faoin dáta <strong>ónarbh</strong> iníoctha í.</td>
    </tr>
    <tr>
        <th>trí</th>
        <td>Bhí fóram ann <strong>trínar</strong> ghnách leis an bhfoireann ceisteanna a ardú.</td>
        <td>Dúnadh an tollán <strong>trínarbh</strong> fhéidir tiomáint.</td>
    </tr>
</tbody>
</table>
++++

=== 7.3.3 {7-3-3-title}

==== A {7-3-3-A-title}

{7-3-3-A-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7Q</strong> {Table7Q-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=3 class="text-xl py-2">{Table7Q-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonant}</th>
        <th>{BeforeVowel}</th>
    </tr></thead>
<tbody>
    <tr>
        <th>sula</th>
        <td><strong>Sular</strong> féidir leis carr a cheannach, caithfidh sé airgead a shábháil.</td>
        <td><strong>Sularb</strong> eol di é a bheith ann, beidh an cat imithe.</td>
    </tr>
    <tr>
        <th>ó</th>
        <td><strong>Ós</strong> rud é gur agat atá eochracha an chairr, is tú a rachaidh chuig an siopa.</td>
        <td><strong>Ós</strong> aici a bheidh an seomra, caithfidh sí féin é a réiteach.</td>
    </tr>
</tbody>
</table>
++++

==== B {7-3-3-B-title}

{7-3-3-B-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7R</strong> {Table7R-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=3>{Table7R-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr></thead>
<tbody>
    <tr>
        <th>sula</th>
        <td><strong>Sular</strong> féidir leis carr a cheannach, caithfidh sé airgead a shábháil.</td>
        <td><strong>Sularb</strong> eol di é a bheith ann, beidh an cat imithe.</td>
    </tr>
    <tr>
        <th>ó</th>
        <td><strong>Ós</strong> rud é gur agat atá eochracha an chairr, is tú a rachaidh chuig an siopa.</td>
        <td><strong>Ós</strong> aici a bheidh an seomra, caithfidh sí féin é a réiteach.</td>
    </tr>
</tbody>
</table>
++++

=== 7.3.4 {7-3-4-title}

{7-3-4-p}

==== A {7-3-4-A-title}

{7-3-4-A-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7S</strong> {Table7S-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=5 class="text-xl py-2">{Table7S-header}</th>
    </tr>
    <tr>
        <th></th>
        <th colspan=2>{BeforeConsonant}</th>
        <th colspan=2>{BeforeVowel}</th>
    </tr></thead>
<tbody>
    <tr>
        <td>{Positive}</td>
        <th>más</th>
        <td>
            <ul>
                <li><strong>Más</strong> mian leat imeacht, is féidir leat.</li>
                <li><strong>Más</strong> mall, is mithid.</li>
            </ul>
        </td>
        <th>más</th>
        <td>
            <ul>
                <li>Fan sa bhaile, <strong>más</strong> amhlaidh is fearr leat é.</li>
                <li><strong>Más</strong> é Séamas atá ann, abair leis teacht anseo.</li>
            </ul>
        </td>
    </tr>
    <tr>
        <td>{Negative}</td>
        <th>mura</th>
        <td>
            <ul>
                <li><strong>Mura</strong> mian léi fanacht, ní gá di.</li>
                <li>Tabhair sampla eile dom, <strong>mura</strong> miste leat.</li>
            </ul>
        </td>
        <th>murab</th>
        <td>
            <ul>
                <li>Bean ard ab ea í, <strong>murab</strong> ionann agus Cáit.</li>
                <li><strong>Murab</strong> áil leis éisteacht, ní gá dó.</li>
            </ul>
        </td>
    </tr>
</tbody>
</table>
++++

==== B {7-3-4-B-title}

{7-3-4-B-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7T</strong> {Table7T-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=4 class="text-xl py-2">{Table7T-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th colspan=2>{BeforeVowelQualified}</th>
    </tr></thead>
<tbody>
    <tr>
        <th></th>
        <th>má ba</th>
        <th>má b'</th>
        <th>má ba</th>
    </tr>
    <tr>
        <td>{Positive}</td>
        <td><strong>Má ba</strong> dhuine macánta é, b'ait an gnó a bhí ar siúl aige.</td>
        <td><strong>Má b'</strong>fhear aitheanta é, ní raibh a fhios agam é.</td>
        <td><strong>Má ba</strong> í a bhí ann, níor aithin sí mé.</td>
    </tr>
    <tr>
        <th></th>
        <th>murar</th>
        <th colspan=2>murarbh</th>
    </tr>
    <tr>
        <td>{Negative}</td>
        <td>
            <ul>
                <li><strong>Murar</strong> chomhalta cláraithe é, ní raibh aon seans aige.</li>
                <li><strong>Murar</strong> shíntiúsóir cláraithe í, ní bhfaigheadh sí an iris sa phost.</li>
            </ul>
        </td>
        <td colspan=2>
            <ul>
                <li><strong>Murarbh</strong> éan é, b'ialtóg a bhí ann.</li>
                <li>Ní bhíodh sí ag imirt <strong>murarbh</strong> áil léi féin é.</li>
            </ul>
        </td>
    </tr>
</tbody>
</table>
++++

=== 7.3.5 {7-3-5-title}

{7-3-5-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7U</strong> {Table7U-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=2 class="text-xl py-2">{Table7U-header}</th>
    </tr>
    <tr>
        <th colspan=2>{BeforeConsonantAndVowel}</th>
    </tr></thead>
<tbody>
    <tr>
        <th>
            Dá + ba &rarr; Dá mba <span class="font-normal">nó</span> Dá mb'
        </th>
        <td>
            <ul>
                <li><strong>Dá mba</strong> mhaith leat é, d'fhéadfainn é a fháil duit.</li>
                <li><strong>Dá mba</strong> é d'athair a déarfadh sin, chreidfinn é.</li>
                <li><strong>Dá mb'</strong>fhear saibhir é, thabharfadh sé síntiús fial uaidh.</li>
                <li><strong>Dá mba</strong> fhreastalaí í, bheadh sí ag obair ar an deireadh seachtaine.</li>
            </ul>
        </td>
    </tr>
</tbody>
</table>
++++

'''

== 7.4 {7-4-title}

{7-4-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Table} 7V</strong> {Table7V-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=5 class="text-xl py-2">{Table7V-header}</th>
    </tr>
    <tr>
        <th></th>
        <th colspan=2>{BeforeConsonant}</th>
        <th colspan=2>{BeforeVowel}</th>
    </tr></thead>
<tbody>
    <tr>
        <td>{Positive}</td>
        <th>gura</th>
        <td>
            <ul>
                <li><strong>Gura</strong> fada buan tú.</li>
                <li><strong>Gura</strong> maith an mhaise dó é.</li>
                <li><strong>Gura</strong> slán an scéal é.</li>
            </ul>
        </td>
        <th class="bg-stone-300">gurab</th>
        <td>
            <ul>
                <li><strong>Gurab</strong> ann romhainn a bheidh sé.</li>
                <li><strong>Gurab</strong> amhlaidh duit.</li>
                <li><strong>Gurab</strong> é barr do leasa é.</li>
            </ul>
        </td>
    </tr>
    <tr>
        <td>{Negative}</td>
        <th class="bg-stone-300">nára</th>
        <td>
            <ul>
                <li><strong>Nára</strong> fíor é.</li>
                <li><strong>Nára</strong> fearrde sibh é.</li>
                <li><strong>Nára</strong> fada go bhfeicfimid a chéile arís.</li>
            </ul>
        </td>
        <th>nárab</th>
        <td>
            <ul>
                <li><strong>Nárab</strong> am amú é.</li>
                <li><strong>Nárab</strong> é a leas é.</li>
                <li><strong>Nárab</strong> é duit.</li>
            </ul>
        </td>
    </tr>
</tbody>
</table>
++++
