= {Chapter} 5 | {chapterTitle}
:showtitle:
:table-caption!:

== 5.1 {5-1-title}

=== 5.1.1 {5-1-1-p}

=== 5.1.2 

{5-1-2-p}

[list-[lower-alpha]]
. {5-1-2-a-p}
. {5-1-2-b-p}

=== 5.1.3

{5-1-3-p}

[list-[lower-alpha]]
. {5-1-3-a-p}
. {5-1-3-b-p}
. {5-1-3-c-p}

=== 5.1.4

{5-1-4-p}

[list-[lower-alpha]]
. {5-1-4-a-p}
. {5-1-4-b-p}

=== 5.1.5 {5-1-5-title}

[list-[lower-alpha]]
. {5-1-5-a-p}
[list-[lower-roman]]
.. {5-1-5-a-i-p}
.. {5-1-5-a-ii-p}
.. {5-1-5-a-iii-p}
. &nbsp;
[list-[lower-roman]]
.. {5-1-5-b-i-p}
.. {5-1-5-b-ii-p}

=== 5.1.6 {5-1-6-title}

{5-1-6-p}

=== 5.1.7 {5-1-7-title}

{5-1-7-p}

=== 5.1.8 {5-1-8-title}

{5-1-8-p}

*{Note}*: {5-1-8-note}

=== 5.1.9 {5-1-9-title}

{5-1-9-p}

=== 5.1.10 {5-1-10-title}

{5-1-10-p}

.*{Table} 5A*  {Table5A-caption}
[.chapter-5]
[%noheader]
[cols="1,1,1"]
|===
a|
[.table-header]
{Table5A-col1}
a| {Table5A-col2}
a| {Table5A-col3}

| {PresentTense}
| molann muid +
tá muid
| molaimid +
táimid

| {PastTense}
| cheannaigh muid +
ní fhaca muid
| cheannaíomar +
ní fhacamar

| {PastHabitualTense}
| d'itheadh muid +
chrádh muid
| d'ithimis +
chráimis

| {FutureTense}
| láimhseoidh muid +
rachaidh muid
| láimhseoimid +
rachaimid

| {ConditionalMood}
| chloisfeadh muid +
nífeadh muid
| chloisfimis +
nífimis

| {SubjunctiveMood}
| go gceanglaí muid +
go dtaga muid
| go gceanglaímid +
go dtagaimid

| {ImperativeModd}
| déanadh muid + 
fágadh muid
| déanaimis + 
fágaimis
|===

'''

== 5.2 {5-2-title}

=== 5.2.1 {5-2-1-title}

[subs=attributes,replacements]
++++
<table class="verb-table w-full">
  <caption>
    <strong>{Table} 5B</strong> {Table5B-caption}
  </caption>
  <tbody>
    <tr>
      <th class="primary-header">Mol</th>
    </tr>
    <tr>
      <td>
        <table class="w-full">
          <colgroup>
            <col class="w-[25%]" />
            <col class="w-[25%]" />
            <col class="w-[25%]" />
            <col class="w-[25%]" />
          </colgroup>
          <thead>
            <tr class="secondary-header-row">
              <th colspan=4>
                {IndicativeMood}
              </th>
            </tr>
            <tr class="tense-row">
              <th>{PresentTense}</th>
              <th>{PastTense}</th>
              <th>{PastHabitualTense}</th>
              <th>{FutureTense}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>molaim</td>
              <td>mhol mé</td>
              <td>mholainn</td>
              <td>molfaidh mé</td>
            </tr>
            <tr>
              <td>molann tú</td>
              <td>mhol tú</td>
              <td>mholtá</td>
              <td>molfaidh tú</td>
            </tr>
            <tr>
              <td>molann sé/sí</td>
              <td>mhol sé/sí</td>
              <td>mholadh sé/sí</td>
              <td>molfaidh sé/sí</td>
            </tr>
            <tr>
              <td>molaimid</td>
              <td>mholamar</td>
              <td>mholaimis</td>
              <td>molfaimid</td>
            </tr>
            <tr>
              <td>molann sibh</td>
              <td>mhol sibh</td>
              <td>mholadh sibh</td>
              <td>molfaidh sibh</td>
            </tr>
            <tr>
              <td>molann siad</td>
              <td>mhol siad</td>
              <td>mholaidís</td>
              <td>molfaidh siad</td>
            </tr>
            <tr>
              <td><em>{abbrev-autonomous}</em> moltar</td>
              <td><em>{abbrev-autonomous}</em> moladh</td>
              <td><em>{abbrev-autonomous}</em> mholtaí</td>
              <td><em>{abbrev-autonomous}</em> molfar</td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td>
        <table class="w-full">
          <colgroup>
            <col class="w-[33%]" />
            <col class="w-[33%]" />
            <col class="w-[33%]" />
          </colgroup>
          <thead>
            <tr class="secondary-header-row">
              <th>{ConditionalMood}</th>
              <th>{PresentSubjunctiveMood}</th>
              <th>{ImperativeMood}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>mholfainn</td>
              <td>go mola mé</td>
              <td>molaim</td>
            </tr>
            <tr>
              <td>mholfá</td>
              <td>go mola tú</td>
              <td>mol</td>
            </tr>
            <tr>
              <td>mholfadh sé/sí</td>
              <td>go mola sé/sí</td>
              <td>moladh sé/sí</td>
            </tr>
            <tr>
              <td>mholfaimis</td>
              <td>go molaimid</td>
              <td>molaimis</td>
            </tr>
            <tr>
              <td>mholfadh sibh</td>
              <td>go mola sibh</td>
              <td>molaigí</td>
            </tr>
            <tr>
              <td>mholfaidís</td>
              <td>go mola siad</td>
              <td>molaidís</td>
            </tr>
            <tr>
              <td><em>{abbrev-autonomous}</em> mholfaí</td>
              <td><em>{abbrev-autonomous}</em> go moltar</td>
              <td><em>{abbrev-autonomous}</em> moltar</td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td>
        <table class="w-full">
           <colgroup>
            <col class="w-[50%]" />
            <col class="w-[50%]" />
          </colgroup>
          <thead>
            <tr class="secondary-header-row">
              <th>{VerbalNoun}</th>
              <th>{VerbalAdjective}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>moladh</td>
              <td>molta</td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
++++

[subs=attributes,replacements]
++++
<table class="verb-table w-full">
  <caption>
    <strong>{Table} 5C</strong> {Table5C-caption}
  </caption>
  <tbody>
    <tr>
      <th class="primary-header">Bris</th>
    </tr>
    <tr>
      <td>
        <table class="w-full">
          <colgroup>
            <col class="w-[25%]" />
            <col class="w-[25%]" />
            <col class="w-[25%]" />
            <col class="w-[25%]" />
          </colgroup>
          <thead>
            <tr class="secondary-header-row">
              <th colspan=4>
                {IndicativeMood}
              </th>
            </tr>
            <tr class="tense-row">
              <th>{PresentTense}</th>
              <th>{PastTense}</th>
              <th>{PastHabitualTense}</th>
              <th>{FutureTense}</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>brisim</td><td>bhris mé</td><td>bhrisinn</td><td>brisfidh mé</td></tr>
            <tr><td>briseann tú</td><td>bhris tú</td><td>bhristeá</td><td>brisfidh tú</td></tr>
            <tr><td>briseann sé/sí</td><td>bhris sé/sí</td><td>bhriseadh sé/sí</td><td>brisfidh sé/sí</td></tr>
            <tr><td>brisimid</td><td>bhriseamar</td><td>bhrisimis</td><td>brisfimid</td></tr>
            <tr><td>briseann sibh</td><td>bhris sibh</td><td>bhriseadh sibh</td><td>brisfidh sibh</td></tr>
            <tr><td>briseann siad</td><td>bhris siad</td><td>bhrisidís</td><td>brisfidh siad</td></tr>
            <tr><td><em>{abbrev-autonomous}</em> bristear</td><td><em>{abbrev-autonomous}</em> briseadh</td><td><em>{abbrev-autonomous}</em> bhristí</td><td><em>{abbrev-autonomous}</em> brisfear</td></tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td>
        <table class="w-full">
          <colgroup>
            <col class="w-[33%]" />
            <col class="w-[33%]" />
            <col class="w-[33%]" />
          </colgroup>
          <thead>
            <tr class="secondary-header-row">
              <th>{ConditionalMood}</th>
              <th>{PresentSubjunctiveMood}</th>
              <th>{ImperativeMood}</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>bhrisfinn</td><td>go mbrise mé</td><td>brisim</td></tr>
            <tr><td>bhrisfeá</td><td>go mbrise tú</td><td>bris</td></tr>
            <tr><td>bhrisfeadh sé/sí</td><td>go mbrise sé/sí</td><td>briseadh sé/sí</td></tr>
            <tr><td>bhrisfimis</td><td>go mbrisimid</td><td>brisimis</td></tr>
            <tr><td>bhrisfeadh sibh</td><td>go mbrise sibh</td><td>brisigí</td></tr>
            <tr><td>bhrisfidís</td><td>go mbrise siad</td><td>brisidís</td></tr>
            <tr><td><em>{abbrev-autonomous}</em> bhrisfí</td><td><em>{abbrev-autonomous}</em> go mbristear</td><td><em>{abbrev-autonomous}</em> bristear</td></tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td>
        <table class="w-full">
           <colgroup>
            <col class="w-[50%]" />
            <col class="w-[50%]" />
          </colgroup>
          <thead>
            <tr class="secondary-header-row">
              <th>{VerbalNoun}</th>
              <th>{VerbalAdjective}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>briseadh</td>
              <td>briste</td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
++++

*{Note}*: {Table5C-Note}
